// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListGeneratedFiles(arg1, arg2) {
  return window['go']['main']['App']['ListGeneratedFiles'](arg1, arg2);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoadSession() {
  return window['go']['main']['App']['LoadSession']();
}

export function ReadGeneratedFile(arg1, arg2) {
  return window['go']['main']['App']['ReadGeneratedFile'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function SelectOutputFolder() {
  return window['go']['main']['App']['SelectOutputFolder']();
}

export function WriteGeneratedFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteGeneratedFile'](arg1, arg2, arg3);
}
