// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function ListGeneratedFiles(arg1:string,arg2:string):Promise<string>;

export function LoadConfig():Promise<string>;

export function LoadSession():Promise<string>;

export function ReadGeneratedFile(arg1:string,arg2:string):Promise<string>;

export function SaveConfig(arg1:string):Promise<void>;

export function SaveSession(arg1:string):Promise<void>;

export function SelectOutputFolder():Promise<string>;

export function WriteGeneratedFile(arg1:string,arg2:string,arg3:string):Promise<string>;
